### ISSUE TITLE
Ability to do and unattended do-release-upgrade

### ISSUE THREAD

**Issue by hackeron** [debops/debops-playbooks#101]
Would be much appreciated when migrating hundreds of servers to a new version of Ubuntu :)

**Comment by drybjed** [comment]
Good idea. I actually have a playbook that would do this - switch all APT sources from `wheezy` to `jessie`. Then an automatic `apt dist-upgrade` could be performed as an optional step. I'll look for it and include in the `tools/` directory.

**Comment by hackeron** [comment]
Would this be the right way to handle this rather than running do-release-upgrade? -- do-release-upgrade deletes obsolete libraries and I'm guessing a bunch of other cleanup?

**Comment by drybjed** [comment]
@hackeron Sure. It's just that `do-release-upgrade` is Ubuntu specific. :-) I can look into using it on Ubuntu systems, of course.

**Comment by hackeron** [comment]
No do-release-upgrade for ubuntu users? :(

**Comment by drybjed** [comment]
@hackeron I'm not sure yet how exactly it works. I'll check on a spare Ubuntu VM first, unless you maybe know if it operates non-interactively and leaves the system in a workable state?

**Comment by hackeron** [comment]
In my script I run:

```bash
apt-get install update-manager-core
apt-get install do-release-upgrade -f DistUpgradeViewNonInteractive
```

To ensure it doesn't ask any questions :)

**Comment by drybjed** [comment]
@hackeron `do-release-upgrade` steps are described in [this AskUbuntu post](http://askubuntu.com/questions/409555/what-does-do-release-upgrade-really-do). What I see is that `do-release-upgrade` basically does the same thing (and more) as the `dist-upgrade.yml` playbook. :-)

Are above commands all the steps you need to do the upgrade?

**Comment by hackeron** [comment]
Yep, it seems to be quite good at removing anything obselete :) - yep, the above steps is what I've used for years and it never fails to update and it never asks any questions with "-f DistUpgradeViewNonInteractive" :)

**Comment by drybjed** [comment]
@hackeron In that cast most of `dist-upgrade` could be discarded for Ubuntu... Does `do-release-upgrade` have any output to capture and send to the admin?

**Comment by hackeron** [comment]
What do you mean discarded? - it seems to do quite a lot of useful stuff. Yes, it gives the output from everything it does, like running apt internally, etc.

**Comment by drybjed** [comment]
@hackeron `do-release-upgrade` handles APT sources, runs `apt-get update`, upgrades packages, removes APT preferences for backports... All you would be interested in is probably the last task which sends an email with output to administrator. :)
