### ISSUE TITLE
No mosh?

### ISSUE THREAD

**Issue by hackeron** [debops/debops-playbooks#102]
I can see mosh on the original ansible-rails and in the video here: https://www.youtube.com/watch?v=rnH3eXDnOMM - but it is gone in debops-playbooks? - I didn't know about mosh prior to watching the video, it looks super useful!

**Comment by drybjed** [comment]
`mosh` never was a part of the playbook. :-) I don't think that it ever requires any configuration...? If you want to have it, easiest way would be to put it in `apt_*_packages` lists, for example to include it on all hosts:

```
apt_packages: [ 'mosh' ]
```
That will make `debops.apt` role install `mosh` package and you should be good after that.

**Comment by hackeron** [comment]
Ah, cool - just thought I would mention it as looking at the description it's something I have been looking for, for a long time and something that should be in the toolkit of any modern sysadmin :)

**Comment by drybjed** [comment]
Watch also this movie: https://www.youtube.com/watch?v=P_Jd5k0S_AQ

**Comment by hackeron** [comment]
Watched! - Fantastic, adding it to my servers :)
