### ISSUE TITLE
Proposed role: debops.cron

### ISSUE THREAD

**Issue by drybjed** [debops/debops-playbooks#15]
This role should help manage cron and crontabs.
- allow creation of custom scripts in `/etc/cron.d/` with support for variables like `MAILTO` (which are lacking in `cron` Ansible module) from a dependency
- perhaps add an option to create or remove entries from user contabs using lineinfile
- randomize cron hourly/daily/weekly/monthly times to avoid huge hit on the whole data center early in the morning (some ideas: https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=373152)

**Comment by ypid** [comment]
I reviewed the available cron roles and [franklinkim.cron](https://github.com/weareinteractive/ansible-cron) looks nice.

**Comment by drybjed** [comment]
Indeed, however it only amounts to just [1 task](https://github.com/weareinteractive/ansible-cron/blob/master/tasks/config.yml) when you strip all the cruft which is not needed for DebOps. It could be added to `debops.console` which became some sort of catch-all for various system and console-related tasks. Which is fine, I think.

**Comment by ypid** [comment]
I think cron should have its own role to allow more flexibility. Not everyone uses all debops roles but maybe just needs an awsome cron role.

**Comment by drybjed** [comment]
The `debops.cron` role exists now, I'm closing this issue as resolved.
