### ISSUE TITLE
Use DebOps "apt_codename" instead of "ansible_distribution" throughout playbooks for Raspbian support

### ISSUE THREAD

**Issue by hleitzell** [debops/debops-playbooks#22]
If bootstrap.yml installs "lsb-release" and apt_codename is setup from within "debops.apt" to be used elsewhere, please use it consistently within all dependencies.  Raspbian shows up as Debian in "ansible_distribution" but correctly shows up in "ansible_lsb" as a separate distribution.   I will submit a pull request for all modules impacted if desired.  

Debian:

``` python
        "ansible_distribution": "Debian",
        "ansible_distribution_major_version": "7",
        "ansible_distribution_release": "wheezy",
        "ansible_distribution_version": "7.6",
...
        "ansible_lsb": {
            "codename": "wheezy",
            "description": "Debian GNU/Linux 7.6 (wheezy)",
            "id": "Debian",
            "major_release": "7",
            "release": "7.6"
        },
```

Raspbian:

``` python
        "ansible_distribution": "Debian",
        "ansible_distribution_major_version": "jessie/sid",
        "ansible_distribution_release": "jessie/sid",
        "ansible_distribution_version": "jessie/sid",
...
        "ansible_lsb": {
            "codename": "jessie",
            "description": "Raspbian GNU/Linux testing (jessie)",
            "id": "Raspbian",
            "major_release": "testing",
            "release": "testing"
        },
```

**Comment by drybjed** [comment]
The `debops.apt` role should now correctly detect Raspbian and configure the repositories. The `debops.core` role does this as well and its facts can be used to detect Raspbian. I'm closing this issue as resolved, if there still are any issues with Raspbian, let me know.
