### ISSUE TITLE
Connecting the dots.

### ISSUE THREAD

**Issue by vCloudernBeer** [debops/debops-playbooks#248]
I was at the debops mailing list site and it said it is better to raise on github.  Mine is more of a question
I have done:
ansible-galaxy install debops.pki
pip install debops
pip install -upgrade pip
debops-update
debops-init <my directory>

What should I do next?  Do I copy  the YAML files into my directory?  Is there a script that I can run that ties these 3 directories together
$HOME/./local/share/debops/debops-playbooks/roles
/etc/ansible/roles
$HOME/<my directory>

Should I be asking this on the mailing list?  Thanks so much.

**Comment by drybjed** [comment]
After installing `debops` scripts and donwloading the playbooks and roles, you should create a new project directory using `debops-init`, for example:
```
debops-init ~/myproject
```
In this directory you will find files required by Ansible, namely `ansible/inventory/hosts`. In there you should specify the hosts that you want to manage. After that, running `debops` command should execute `ansible-playbook` with the default DebOps playbook. You don't need to copy the playbooks from `~/.local/share/debops/`, the script will make sure that they are passed to `ansible-playbook` by itself.

There's a [Getting Started guide](http://docs.debops.org/en/latest/debops-playbooks/docs/guides/getting-started.html) which explains in more detail this process, you should check it out.

NB.: you can use either the mailing list (there's a [a new one](https://lists.debops.org/) or the GitHub issues to ask the questions. The problem I see with GitHub issues though, is that each role has its own set of issues. Without being a member of the DebOps organization, or subscribing to the role repository itself, you won't get notifications about issues you might care about. So I encourage either to watch the role repositories relevant to you, or send questions to the mailing list where more people can see them.

**Comment by vCloudernBeer** [comment]
Thanks so much.  I feel more comfortable asking questions on mailing list than here in GitHub. I was desperate so I ask here.  Thanks for the pointers and have a nice weekend.
