### ISSUE TITLE
Proposed roles: debops.environment and debops.apt_proxy

### ISSUE THREAD

**Issue by ypid** [debops/debops-playbooks#271]
- [x] `debops.environment`: Manage system environment variables
- [ ] `debops.apt_proxy`: Configures APT to use a HTTP Proxy server

~~debops.system_proxy~~

Refs: IRC and mailing list thread: https://groups.io/g/debops/message/79

**Comment by drybjed** [comment]
The proxy configuration is done via environment variables configured in `/etc/environment` and `/etc/profile.d/`, so why not just settle on say, `debops.environment` role for this? It makes it more general. This role would probably be at the top of `common.yml` playbook to make the environent variables present as soon as possible.

`debops.apt_proxy` is a good idea, some tasks from `debops.apt` could be moved there.

**Comment by drybjed** [comment]
The [debops.environment](https://github.com/debops/ansible-environment/) role has been created.

**Comment by ypid** [comment]
[debops.apt_proxy](https://github.com/debops/ansible-apt_proxy) is also in place. Closing :wink:
