### ISSUE TITLE
[Question] What software was used to generate a dependency graph?

### ISSUE THREAD

**Issue by it-praktyk** [debops/debops-playbooks#355]
I would like know what software was used to generate a dependency graph what is built-in in the README.md file for the [debops/debops-playbooks](https://github.com/debops/debops-playbooks/) repository.

Thank you.

**Comment by drybjed** [comment]
Hello. It was [ansigenome](https://github.com/nickjj/ansigenome).

**Comment by it-praktyk** [comment]
Thank you!
