### ISSUE TITLE
Comment macros in debops__tpl_macros.j2

### ISSUE THREAD

**Issue by ganto** [debops/debops-playbooks#363]
Currently I'm trying to figure out, if there are some macros available in `debops__tpl_macros.j2` which I could re-use for the `checkmk_server` role. However, I'm a bit struggling to understand the purpose of some of the macros, e.g. `get_realm_yaml_list()`.

Would it be to much of a hassle to properly document them in a short comment, as you usually would with any other code function? Here's an example what I mean: https://github.com/debops-contrib/ansible-checkmk_server/blob/master/templates/macros/checkmk_config.j2#L168

What should be commented in my opinion are:
- short summary what it does
- return value
- (optionally) arguments
- (optionally) when to use?

Would it be ok, if I send patches for the more trivial one, so you can see what I mean?

**Comment by drybjed** [comment]
Sounds good to me. PR away.
