### ISSUE TITLE
Support secure connections to remote databases (MySQL, PostgreSQL)

### ISSUE THREAD

**Issue by drybjed** [debops/debops-playbooks#88]
Support for encrypted connections to remote databases is needed for high availability and failover if necessary. Check if it can be done with TLS support in database servers (support in client applications might be required) or investigate an easy way to do it with `stunnel` managed by a separate role.

**Comment by ypid** [comment]
@drybjed Seems you did this for both DB servers, yay :) I guess you can close this then?
